### ISSUE TITLE
is there any search funcionality for country

### ISSUE THREAD

**Issue by lsdev200** [goveo/react-international-phone#182] opened 2024-05-08 06:09 UTC
is there any search funcionality for country? i want be able to search country from dropdown list of country.
waiting for reply
thanks

**Comment by goveo** [comment] 2024-05-18 15:32
Not yet, sorry.
You can search country by starting typing when the country-selector is open (similar to native HTML `<select>`).

Closing this issue as a duplicate of #134

**Closed by goveo** 2024-05-18 15:32 UTC
