### ISSUE TITLE
Not all countries represented

### ISSUE THREAD

**Issue by artemklishch** [goveo/react-international-phone#148] opened 2024-01-22 14:35 UTC
Hello!

I use the library 'country-region-data', because I also need the regions/states data for every country.
Bu I also have the phone field.
There are some differences in lists of countries, provided by the  'country-region-data' and your library. Only some countries. 
For example: when I choose the country from the  'country-region-data' , American Samoa - there is no that country in the 'defaultCountries' variable, imported from the 'react-international-phone' library.
Is it possible to provide there absent countries? Or add regions data to the 'react-international-phone' for every country?

Thank you!

**Comment by goveo** [comment] 2024-01-26 15:25
@artemklishch Hey!
Sorry, but it's not planned to add all ISO-3166-2 countries' support in the near time.
You can extend `defaultCountries` with the countries you need:
https://react-international-phone.vercel.app/docs/Usage/ModifyCountries
Just pass your updated country-data JSON to the `countries` prop.

**Comment by artemklishch** [comment] 2024-01-26 15:46
Thanks for the answer!

пт, 26 янв. 2024 г. в 17:25, Yurii Brusentsov ***@***.***>:

**Comment by goveo** [comment] 2024-04-20 18:03
Closed as duplicate of https://github.com/goveo/react-international-phone/issues/53

**Closed by goveo** 2024-04-20 18:03 UTC
