### ISSUE TITLE
Auto fill does not work correctly

### ISSUE THREAD

**Issue by whitetown** [goveo/react-international-phone#91] opened 2023-09-04 14:36 UTC
**Describe the bug**
My browser remembers phone numbers I entered before. 
Numbers could be with or without country code.
i.e.
0919044123
+421919044123

When I select such a number in Chrome/Safari either on mobile or desktop, the number inserted as +919044113 or +0919044123

The current country code is ignored and/or not updated

**To Reproduce**

1. Just try to auto fill the number in any browser

**Expected behavior**
I would expect that 
- if autofill number is without country code then the selected country will remain unchanged and number will be prefixed with the country code.
- if autofill number is with country code, then it will inserted as is and the country/flag changes accordingly 

**Desktop (please complete the following information):**

- OS: OSX 
- Browser: chrome, safari

**Smartphone (please complete the following information):**

- Device: iPhone
- OS: iOS latest

**Comment by goveo** [comment] 2023-10-22 14:56
@whitetown
Autofill logic was updated in v4.0.0.
Please check if it's working as expected.
I will close the issue for now, feel free to reopen it if anything seems to be wrong

**Closed by goveo** 2023-10-22 14:56 UTC
Labels: bug

**Comment by alexookah** [comment] 2024-01-25 23:27
@goveo 
When using autofill for a phone number input field, the displayed country flag does not update to match the autofilled number's country code. Additionally, the expected formatting (including spacing) is not applied until the field is manually edited.

tested in latest 4.2.1 version.

### Steps to Reproduce
Set a default country code (e.g., +44).
Use autofill to input a phone number with a different country code (e.g., +301234567890).
Observe that the text updates correctly to +301234567890.
Notice that the country flag remains unchanged (still showing the default country's flag).
The expected phone number formatting (e.g., +30 1234567890) does not appear until some manual editing is done in the text field.

**Comment by goveo** [comment] 2024-01-26 15:10
@alexookah Can you provide more info about your use case?
I tried to reproduce the issue, but it works fine for me with this config:
```tsx
export const Test = () => {
  const [phone, setPhone] = useState('');

  return (
    <div>
      <span>Phone: {phone}</span>
      <form
        onSubmit={(e) => {
          e.preventDefault();
        }}
      >
        <PhoneInput
          value={phone}
          onChange={setPhone}
          defaultCountry="gb"
          name="phone"
          disableDialCodePrefill
        />
        <button>Submit</button>
      </form>
    </div>
  );
};
```

What browser and OS do you use?
It would be great if you could reproduce this with a small example in [codesandbox](https://codesandbox.io/) 🙏

**Comment by alexookah** [comment] 2024-01-26 15:27
Mainly I managed to reproduce this with copy pasting in browser. and autofill in iOS device.
I will try if I can manage to make this in codesandbox including a screen capture

**Comment by goveo** [comment] 2024-02-04 16:57
Thanks for the demo, checking it..

**Comment by goveo** [comment] 2024-02-06 22:22
Seems like it's related to Safari:
https://github.com/facebook/react/issues/2125

**Comment by alexookah** [comment] 2024-02-06 22:34
I do have wrapped the input phone in <form> element
