### ISSUE TITLE
Feat: Introduce Search Input in Country Dropdown

### ISSUE THREAD

**Issue by evertoont** [goveo/react-international-phone#140] opened 2023-12-22 18:29 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the library only has a search feature without an input field, and I believe this might not be very intuitive, making it challenging for less experienced users to quickly locate and select the desired country code. This leads to a frustrating experience for those who need to find the country code promptly.

**Describe the solution you'd like**
I would like to request the addition of a search field within the country dropdown. This would allow users to enter the name of the desired country, triggering a corresponding filter in the list of country codes. This enhancement would make the selection process faster and more accurate.

**Describe alternatives you've considered**
A viable alternative would be to retain the existing search functionality and introduce a property that enables direct input within the dropdown, thereby disabling the default search mode.

**Additional context**
This improvement would provide a smoother experience for users dealing with international phone numbers, saving time and reducing frustration when searching for specific country codes

**Comment by goveo** [comment] 2024-02-05 11:37
Duplicate of [goveo/react-international-phone#134](https://github.com/goveo/react-international-phone/issues/134)

**Closed by goveo** 2024-02-05 11:37 UTC
